/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AlgorithmDisplay: typeof import("./src/components/AlgorithmDisplay/AlgorithmDisplay.vue")["default"];
    BackTop: typeof import("./src/components/BackTop/BackTop.vue")["default"];
    Banner: typeof import("./src/components/Banner/Banner.vue")["default"];
    BannerCoverText: typeof import("./src/components/BannerCoverText/BannerCoverText.vue")["default"];
    Comment: typeof import("./src/components/Comment/Comment.vue")["default"];
    CommentBox: typeof import("./src/components/Comment/src/comment-box.vue")["default"];
    CommentList: typeof import("./src/components/Comment/src/comment-list.vue")["default"];
    ContentBox: typeof import("./src/components/Comment/src/content-box.vue")["default"];
    ElAutocomplete: typeof import("element-plus/es")["ElAutocomplete"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBacktop: typeof import("element-plus/es")["ElBacktop"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCarousel: typeof import("element-plus/es")["ElCarousel"];
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElProgress: typeof import("element-plus/es")["ElProgress"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    Footer: typeof import("./src/components/Footer/Footer.vue")["default"];
    Header: typeof import("./src/components/Header/Header.vue")["default"];
    IndexIntroduce: typeof import("./src/components/IndexIntroduce/IndexIntroduce.vue")["default"];
    IndexService: typeof import("./src/components/IndexIntroduce/IndexService.vue")["default"];
    Operation: typeof import("./src/components/Comment/src/operation.vue")["default"];
    PointCloud: typeof import("./src/components/PointCloud/PointCloud.vue")["default"];
    QA: typeof import("./src/components/QA/QA.vue")["default"];
    ReplyBox: typeof import("./src/components/Comment/src/reply-box.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchBanner: typeof import("./src/components/SearchBanner/SearchBanner.vue")["default"];
    Slide: typeof import("./src/components/Slide/Slide.vue")["default"];
    UpLoad: typeof import("./src/components/UpLoad/UpLoad.vue")["default"];
    UserInfo: typeof import("./src/components/Comment/src/user-info.vue")["default"];
  }
}
