/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		AlgorithmDisplay: typeof import('./src/components/AlgorithmDisplay/AlgorithmDisplay.vue')['default']
		BackTop: typeof import('./src/components/BackTop/BackTop.vue')['default']
		Banner: typeof import('./src/components/Banner/Banner.vue')['default']
		BreadCrumbs: typeof import('./src/components/BreadCrumbs/BreadCrumbs.vue')['default']
		Contributor: typeof import('./src/components/Contributor/Contributor.vue')['default']
		ElBacktop: typeof import('element-plus/es')['ElBacktop']
		ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
		ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
		ElButton: typeof import('element-plus/es')['ElButton']
		ElCard: typeof import('element-plus/es')['ElCard']
		ElCarousel: typeof import('element-plus/es')['ElCarousel']
		ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
		ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
		ElCol: typeof import('element-plus/es')['ElCol']
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
		ElForm: typeof import('element-plus/es')['ElForm']
		ElFormItem: typeof import('element-plus/es')['ElFormItem']
		ElImage: typeof import('element-plus/es')['ElImage']
		ElInput: typeof import('element-plus/es')['ElInput']
		ElOption: typeof import('element-plus/es')['ElOption']
		ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
		ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
		ElRow: typeof import('element-plus/es')['ElRow']
		ElSelect: typeof import('element-plus/es')['ElSelect']
		ElUpload: typeof import('element-plus/es')['ElUpload']
		Footer: typeof import('./src/components/Footer/Footer.vue')['default']
		Header: typeof import('./src/components/Header/Header.vue')['default']
		ImageOption: typeof import('./src/components/ImageOption/ImageOption.vue')['default']
		RouterLink: typeof import('vue-router')['RouterLink']
		RouterView: typeof import('vue-router')['RouterView']
		Search: typeof import('./src/components/Search/Search.vue')['default']
		SearchBanner: typeof import('./src/components/SearchBanner/SearchBanner.vue')['default']
		Slide: typeof import('./src/components/Slide/Slide.vue')['default']
	}
}
